const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Touch: 0},
	{HP: 0},
	{MaxHP: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{Flash: 0},
	{Player: 0},
	{Bullet: 0},
	{Goblin: 0},
	{DestroyOutsideLayout: 0},
	{Spell: 0},
	{Fade: 0},
	{SparkFlash: 0},
	{Mouse: 0},
	{Hpbar: 0},
	{HpbarEnemy: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Goblin: class extends self.ISpriteInstance {},
	Spell: class extends self.ISpriteInstance {},
	SparkFlash: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Hpbar: class extends self.ISpriteInstance {},
	HpbarEnemy: class extends self.ISpriteInstance {}
}