const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Flash,
		C3.Behaviors.Tween,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Touch: 0},
	{HP: 0},
	{MaxHP: 0},
	{BoundToLayout: 0},
	{Player: 0},
	{StartX: 0},
	{Amplitude: 0},
	{Period: 0},
	{Direction: 0},
	{pop: 0},
	{Flash: 0},
	{Tween: 0},
	{Goblin: 0},
	{Bullet: 0},
	{Spell: 0},
	{Fade: 0},
	{SparkFlash: 0},
	{Mouse: 0},
	{Hpbar: 0},
	{HpbarEnemy: 0},
	{Text: 0},
	{Tilemap: 0},
	{TiledBackground2: 0},
	{RetryButton: 0},
	{TiledBackground3: 0},
	{DamageText: 0},
	{Solid: 0},
	{Wall: 0},
	{ScoreText: 0},
	{TiledBackground4: 0},
	{TiledBackground5: 0},
	{TiledBackground6: 0},
	{SparkFlash2: 0},
	{Variable1: 0},
	{ono: 0},
	{GameOver: 0},
	{Score: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Player: class extends self.ISpriteInstance {},
	Goblin: class extends self.ISpriteInstance {},
	Spell: class extends self.ISpriteInstance {},
	SparkFlash: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Hpbar: class extends self.ISpriteInstance {},
	HpbarEnemy: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	RetryButton: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	DamageText: class extends self.ITextInstance {},
	Wall: class extends self.ISpriteInstance {},
	ScoreText: class extends self.ITextInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	TiledBackground5: class extends self.ITiledBackgroundInstance {},
	TiledBackground6: class extends self.ITiledBackgroundInstance {},
	SparkFlash2: class extends self.ISpriteInstance {},
	ono: class extends self.ISpriteInstance {}
}